version: "3.7"
services: 
  app:
    container_name: spring-backend
    image: springboot-postgresql
    build: ./
    ports: 
      - "8080:8080"
    environment:
      - DB_SERVER=db
      - POSTGRES_DB=employeeAdministration
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on: 
      - db
  db:
    container_name: postgres
    image: postgres
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=employeeAdministration